//ACTION TYPES
export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const GET_ERRORS = 'GET_ERRORS';

export const BOOK_APPOINTMENT = 'BOOK_APPOINTMENT'; 
export const GET_APPOINTMENT = 'GET_APPOINTMENT'; 
export const GET_APPOINTMENTS = 'GET_APPOINTMENTS'; 
export const UPDATE_APPOINTMENT = 'UPDATE_APPOINTMENT'; 
export const DELETE_APPOINTMENT = 'DELETE_APPOINTMENT'; 

export const ADD_CONSULTANT = 'ADD_CONSULTANT'; 
export const GET_CONSULTANTS = 'GET_CONSULTANTS'; 
export const GET_CONSULTANT = 'GET_CONSULTANT'; 
export const UPDATE_CONSULTANT = 'UPDATE_CONSULTANT'; 
export const DELETE_CONSULTANT = 'DELETE_CONSULTANT'; 
